/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.FornecedorController;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pedro
 */
public class InterfaceFornecedor extends javax.swing.JFrame {

    URL url = this.getClass().getResource("/Imagens/Icone.png");  
    Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);  
    private final FornecedorController fornecedorController = new FornecedorController();
    private ResultSet rst;
    int cont=0;
    private String nomeAntigo,cnpjAntigo, enderecoAntigo, telAntigo, outrosAntigo;
    private int codigoAntigo;
    private float precoAntigo,quantidadeAntigo;
    
    /**
     * Creates new form InterfaceFornecedores
     */
    public InterfaceFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgConfirmaRmv = new javax.swing.JDialog();
        painelSair = new javax.swing.JPanel();
        btSimRmv = new javax.swing.JButton();
        btNaoRmv = new javax.swing.JButton();
        painelFornecedor = new javax.swing.JPanel();
        btRemoverFornecedor = new javax.swing.JButton();
        btAlterarFornecedor = new javax.swing.JButton();
        btConsultarFornecedor = new javax.swing.JButton();
        btAddFornecedor = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        painelCamadaFornecedor = new javax.swing.JLayeredPane();
        painelAddFornecedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoRazaoSocialAdd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoEnderecoAdd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btAdicionar = new javax.swing.JButton();
        btLimparAdd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoDescricaoAdd = new javax.swing.JTextArea();
        campoNumAdd = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        campoComplementoAdd = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        campoBairroAdd = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        campoCidadeAdd = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        comboUf = new javax.swing.JComboBox<>();
        campoCnpjAdd = new javax.swing.JFormattedTextField();
        campoTelAdd = new javax.swing.JFormattedTextField();
        painelRmvFornecedor = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboFormaRmv = new javax.swing.JComboBox<>();
        lbFormaPesquisaRmv = new javax.swing.JLabel();
        campoNomeCodRmv = new javax.swing.JTextField();
        btBuscarRmv = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbFornecedorRmv = new javax.swing.JTable();
        btRmvFornecedor = new javax.swing.JButton();
        painelAltFornecedor = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        comboFormaAlt = new javax.swing.JComboBox<>();
        lbFormaPesquisaAlt = new javax.swing.JLabel();
        campoNomeCodAlt = new javax.swing.JTextField();
        btBuscarAlt = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbFornecedorAlt = new javax.swing.JTable();
        painelPsqFornecedor = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbFormaPesquisa = new javax.swing.JLabel();
        campoNomeCod = new javax.swing.JTextField();
        btBuscarFornecedor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFornecedor = new javax.swing.JTable();
        comboFormaPesquisa = new javax.swing.JComboBox<>();

        msgConfirmaRmv.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        msgConfirmaRmv.setTitle("Deseja realmente remover o fornecedor?");
        msgConfirmaRmv.setAlwaysOnTop(true);
        msgConfirmaRmv.setIconImage(iconeTitulo);
        msgConfirmaRmv.setLocation(new java.awt.Point(500, 250));
        msgConfirmaRmv.setMinimumSize(new java.awt.Dimension(265, 70));
        msgConfirmaRmv.setResizable(false);

        painelSair.setPreferredSize(new java.awt.Dimension(265, 70));

        btSimRmv.setText("Sim");
        btSimRmv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSimRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimRmvActionPerformed(evt);
            }
        });

        btNaoRmv.setText("Não");
        btNaoRmv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btNaoRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNaoRmvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelSairLayout = new javax.swing.GroupLayout(painelSair);
        painelSair.setLayout(painelSairLayout);
        painelSairLayout.setHorizontalGroup(
            painelSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSairLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btSimRmv, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addComponent(btNaoRmv, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        painelSairLayout.setVerticalGroup(
            painelSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSairLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSimRmv)
                    .addComponent(btNaoRmv))
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout msgConfirmaRmvLayout = new javax.swing.GroupLayout(msgConfirmaRmv.getContentPane());
        msgConfirmaRmv.getContentPane().setLayout(msgConfirmaRmvLayout);
        msgConfirmaRmvLayout.setHorizontalGroup(
            msgConfirmaRmvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        msgConfirmaRmvLayout.setVerticalGroup(
            msgConfirmaRmvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento de fornecedores");
        setLocation(new java.awt.Point(100, 100));
        setResizable(false);

        this.painelAddFornecedor.setVisible(true);
        this.painelRmvFornecedor.setVisible(false);
        this.painelAltFornecedor.setVisible(false);
        this.painelPsqFornecedor.setVisible(false);

        btRemoverFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Remover produto.png"))); // NOI18N
        btRemoverFornecedor.setText("Remover fornecedor");
        btRemoverFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRemoverFornecedor.setMaximumSize(new java.awt.Dimension(389, 265));
        btRemoverFornecedor.setMinimumSize(new java.awt.Dimension(389, 265));
        btRemoverFornecedor.setPreferredSize(new java.awt.Dimension(389, 265));
        btRemoverFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverFornecedorActionPerformed(evt);
            }
        });

        btAlterarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Editar produto.png"))); // NOI18N
        btAlterarFornecedor.setText("Alterar fornecedor");
        btAlterarFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAlterarFornecedor.setMaximumSize(new java.awt.Dimension(389, 265));
        btAlterarFornecedor.setMinimumSize(new java.awt.Dimension(389, 265));
        btAlterarFornecedor.setPreferredSize(new java.awt.Dimension(389, 265));
        btAlterarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarFornecedorActionPerformed(evt);
            }
        });

        btConsultarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Consultar produto.png"))); // NOI18N
        btConsultarFornecedor.setText("Consultar fornecedor");
        btConsultarFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btConsultarFornecedor.setMaximumSize(new java.awt.Dimension(389, 265));
        btConsultarFornecedor.setMinimumSize(new java.awt.Dimension(389, 265));
        btConsultarFornecedor.setPreferredSize(new java.awt.Dimension(389, 265));
        btConsultarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarFornecedorActionPerformed(evt);
            }
        });

        btAddFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Adicionar produto.png"))); // NOI18N
        btAddFornecedor.setText("Adicionar fornecedor");
        btAddFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAddFornecedor.setEnabled(false);
        btAddFornecedor.setMaximumSize(new java.awt.Dimension(389, 265));
        btAddFornecedor.setMinimumSize(new java.awt.Dimension(389, 265));
        btAddFornecedor.setPreferredSize(new java.awt.Dimension(389, 265));
        btAddFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddFornecedorActionPerformed(evt);
            }
        });

        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Voltar.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        painelCamadaFornecedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));

        jLabel1.setText("Razão social*:");

        campoRazaoSocialAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoRazaoSocialAddKeyReleased(evt);
            }
        });

        jLabel2.setText("CNPJ*:");

        campoEnderecoAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoEnderecoAddKeyTyped(evt);
            }
        });

        jLabel3.setText("Endereço:");

        jLabel5.setText("Observações");

        btAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Finalizar adicionado.png"))); // NOI18N
        btAdicionar.setText("Adicionar");
        btAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAdicionar.setEnabled(false);
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btLimparAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Limpar campos.png"))); // NOI18N
        btLimparAdd.setText("Limpar campos");
        btLimparAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLimparAdd.setEnabled(false);
        btLimparAdd.setMaximumSize(new java.awt.Dimension(139, 31));
        btLimparAdd.setMinimumSize(new java.awt.Dimension(139, 31));
        btLimparAdd.setPreferredSize(new java.awt.Dimension(139, 31));
        btLimparAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparAddActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("ADICIONAR FORNECEDOR");

        campoDescricaoAdd.setColumns(20);
        campoDescricaoAdd.setRows(5);
        jScrollPane2.setViewportView(campoDescricaoAdd);

        campoNumAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNumAddKeyTyped(evt);
            }
        });

        jLabel12.setText("Número:");

        jLabel13.setText("Complemento:");

        jLabel14.setText("Cidade:");

        campoBairroAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoBairroAddKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoBairroAddKeyTyped(evt);
            }
        });

        jLabel15.setText("Bairro:");

        campoCidadeAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCidadeAddKeyTyped(evt);
            }
        });

        jLabel16.setText("UF:");

        jLabel17.setText("Tel/Cel*:");

        comboUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        try {
            campoCnpjAdd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCnpjAdd.setEnabled(false);
        campoCnpjAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoCnpjAddKeyReleased(evt);
            }
        });

        try {
            campoTelAdd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoTelAdd.setEnabled(false);
        campoTelAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoTelAddKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout painelAddFornecedorLayout = new javax.swing.GroupLayout(painelAddFornecedor);
        painelAddFornecedor.setLayout(painelAddFornecedorLayout);
        painelAddFornecedorLayout.setHorizontalGroup(
            painelAddFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAddFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAddFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAddFornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(880, 880, 880))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAddFornecedorLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(painelAddFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelAddFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(painelAddFornecedorLayout.createSequentialGroup()
                                    .addComponent(btLimparAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(btAdicionar))
                                .addGroup(painelAddFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelAddFornecedorLayout.createSequentialGroup()
                                        .addGroup(painelAddFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAddFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(painelAddFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(painelAddFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(campoRazaoSocialAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(painelAddFornecedorLayout.createSequentialGroup()
                                                    .addGroup(painelAddFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(painelAddFornecedorLayout.createSequentialGroup()
                                                            .addComponent(campoEnderecoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jLabel12)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(campoNumAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jLabel13))
                                                        .addGroup(painelAddFornecedorLayout.createSequentialGroup()
                                                            .addComponent(campoBairroAdd)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jLabel14)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(campoCidadeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(painelAddFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(campoComplementoAdd)
                                                        .addGroup(painelAddFornecedorLayout.createSequentialGroup()
                                                            .addComponent(jLabel16)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(comboUf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                            .addComponent(campoCnpjAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoTelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        painelAddFornecedorLayout.setVerticalGroup(
            painelAddFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAddFornecedorLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(painelAddFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoRazaoSocialAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAddFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCnpjAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAddFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEnderecoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoComplementoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAddFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBairroAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCidadeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(comboUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAddFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(campoTelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelAddFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimparAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("REMOVER FORNECEDOR");

        jLabel9.setText("Forma de pesquisa");

        comboFormaRmv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos fornecedores", "Razão social do fornecedor", "Código do fornecedor" }));
        comboFormaRmv.setToolTipText("");
        comboFormaRmv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboFormaRmv.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFormaRmvItemStateChanged(evt);
            }
        });

        lbFormaPesquisaRmv.setText("Todos fornecedores");

        campoNomeCodRmv.setEnabled(false);
        campoNomeCodRmv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNomeCodRmvKeyTyped(evt);
            }
        });

        btBuscarRmv.setText("Buscar");
        btBuscarRmv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btBuscarRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarRmvActionPerformed(evt);
            }
        });

        tbFornecedorRmv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Razão social", "CNPJ", "Endereço", "Telefone/Celular", "Data de cadastro", "Observações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbFornecedorRmv.getTableHeader().setReorderingAllowed(false);
        tbFornecedorRmv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFornecedorRmvMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbFornecedorRmv);

        btRmvFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Finalizar removido.png"))); // NOI18N
        btRmvFornecedor.setText("Remover fornecedor");
        btRmvFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRmvFornecedor.setEnabled(false);
        btRmvFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRmvFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelRmvFornecedorLayout = new javax.swing.GroupLayout(painelRmvFornecedor);
        painelRmvFornecedor.setLayout(painelRmvFornecedorLayout);
        painelRmvFornecedorLayout.setHorizontalGroup(
            painelRmvFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRmvFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelRmvFornecedorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(painelRmvFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelRmvFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1079, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbFormaPesquisaRmv)
                        .addGroup(painelRmvFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(painelRmvFornecedorLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboFormaRmv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelRmvFornecedorLayout.createSequentialGroup()
                                .addComponent(campoNomeCodRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBuscarRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btRmvFornecedor, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26))
        );
        painelRmvFornecedorLayout.setVerticalGroup(
            painelRmvFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRmvFornecedorLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(painelRmvFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboFormaRmv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbFormaPesquisaRmv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelRmvFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNomeCodRmv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarRmv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRmvFornecedor)
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("ALTERAR FORNECEDOR");

        jLabel11.setText("Forma de pesquisa");

        comboFormaAlt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos fornecedores", "Razão social do fornecedor", "Código do fornecedor" }));
        comboFormaAlt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboFormaAlt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFormaAltItemStateChanged(evt);
            }
        });

        lbFormaPesquisaAlt.setText("Todos fornecedores");

        campoNomeCodAlt.setEnabled(false);
        campoNomeCodAlt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNomeCodAltKeyTyped(evt);
            }
        });

        btBuscarAlt.setText("Buscar");
        btBuscarAlt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btBuscarAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarAltActionPerformed(evt);
            }
        });

        tbFornecedorAlt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Razão social", "CNPJ", "Endereço", "Telefone/Celular", "Data de cadastro", "Observações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbFornecedorAlt.getTableHeader().setReorderingAllowed(false);
        tbFornecedorAlt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFornecedorAltMouseClicked(evt);
            }
        });
        tbFornecedorAlt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbFornecedorAltPropertyChange(evt);
            }
        });
        jScrollPane4.setViewportView(tbFornecedorAlt);

        javax.swing.GroupLayout painelAltFornecedorLayout = new javax.swing.GroupLayout(painelAltFornecedor);
        painelAltFornecedor.setLayout(painelAltFornecedorLayout);
        painelAltFornecedorLayout.setHorizontalGroup(
            painelAltFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAltFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAltFornecedorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(painelAltFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1079, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFormaPesquisaAlt)
                    .addGroup(painelAltFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(painelAltFornecedorLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboFormaAlt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelAltFornecedorLayout.createSequentialGroup()
                            .addComponent(campoNomeCodAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btBuscarAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26))
        );
        painelAltFornecedorLayout.setVerticalGroup(
            painelAltFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAltFornecedorLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(painelAltFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(comboFormaAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbFormaPesquisaAlt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAltFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNomeCodAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarAlt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelPsqFornecedor.setPreferredSize(new java.awt.Dimension(1113, 395));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("CONSULTAR FORNECEDOR");

        jLabel7.setText("Forma de pesquisa");

        lbFormaPesquisa.setText("Todos fornecedores");

        campoNomeCod.setEnabled(false);
        campoNomeCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNomeCodKeyTyped(evt);
            }
        });

        btBuscarFornecedor.setText("Buscar");
        btBuscarFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btBuscarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarFornecedorActionPerformed(evt);
            }
        });

        tbFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Razão social", "CNPJ", "Endereço", "Telefone/Celular", "Data de cadastro", "Observações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbFornecedor.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbFornecedor);

        comboFormaPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos fornecedores", "Razão social do fornecedor", "Código do fornecedor" }));
        comboFormaPesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboFormaPesquisa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFormaPesquisaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout painelPsqFornecedorLayout = new javax.swing.GroupLayout(painelPsqFornecedor);
        painelPsqFornecedor.setLayout(painelPsqFornecedorLayout);
        painelPsqFornecedorLayout.setHorizontalGroup(
            painelPsqFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPsqFornecedorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
                .addGap(26, 26, 26))
            .addGroup(painelPsqFornecedorLayout.createSequentialGroup()
                .addGroup(painelPsqFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPsqFornecedorLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(painelPsqFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbFormaPesquisa)
                            .addGroup(painelPsqFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(painelPsqFornecedorLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboFormaPesquisa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelPsqFornecedorLayout.createSequentialGroup()
                                    .addComponent(campoNomeCod, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btBuscarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(painelPsqFornecedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelPsqFornecedorLayout.setVerticalGroup(
            painelPsqFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPsqFornecedorLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(painelPsqFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboFormaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbFormaPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPsqFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNomeCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelCamadaFornecedor.setLayer(painelAddFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelCamadaFornecedor.setLayer(painelRmvFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelCamadaFornecedor.setLayer(painelAltFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelCamadaFornecedor.setLayer(painelPsqFornecedor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelCamadaFornecedorLayout = new javax.swing.GroupLayout(painelCamadaFornecedor);
        painelCamadaFornecedor.setLayout(painelCamadaFornecedorLayout);
        painelCamadaFornecedorLayout.setHorizontalGroup(
            painelCamadaFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAddFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelCamadaFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelRmvFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelCamadaFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelAltFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelCamadaFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelPsqFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE))
        );
        painelCamadaFornecedorLayout.setVerticalGroup(
            painelCamadaFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAddFornecedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelCamadaFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelRmvFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelCamadaFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelAltFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelCamadaFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelPsqFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelFornecedorLayout = new javax.swing.GroupLayout(painelFornecedor);
        painelFornecedor.setLayout(painelFornecedorLayout);
        painelFornecedorLayout.setHorizontalGroup(
            painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFornecedorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelFornecedorLayout.createSequentialGroup()
                        .addComponent(btAddFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(102, 102, 102)
                        .addComponent(btRemoverFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(102, 102, 102)
                        .addComponent(btAlterarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(102, 102, 102)
                        .addComponent(btConsultarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(painelCamadaFornecedor)
                    .addGroup(painelFornecedorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btVoltar)))
                .addGap(19, 19, 19))
        );
        painelFornecedorLayout.setVerticalGroup(
            painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFornecedorLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btAlterarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, Short.MAX_VALUE)
                        .addComponent(btConsultarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, Short.MAX_VALUE))
                    .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btAddFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, Short.MAX_VALUE)
                        .addComponent(btRemoverFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelCamadaFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void limparCamposAdd(){
        this.campoRazaoSocialAdd.setText("");
        this.campoEnderecoAdd.setText("");
        this.campoBairroAdd.setText("");
        this.campoNumAdd.setText("");
        this.campoCidadeAdd.setText("");
        this.campoComplementoAdd.setText("");
        this.comboUf.setSelectedItem(-1);
        this.campoCnpjAdd.setText("");
        this.campoDescricaoAdd.setText("");
        this.campoTelAdd.setText("");
        this.campoTelAdd.setEnabled(false);
        this.campoCnpjAdd.setEnabled(false);
    }
    
    private void limparCamposPsq(){
        this.campoNomeCod.setText("");
        this.comboFormaAlt.setSelectedIndex(0);
        this.comboFormaPesquisa.setSelectedIndex(0);
        this.comboFormaRmv.setSelectedIndex(0);
        DefaultTableModel dm = (DefaultTableModel) this.tbFornecedor.getModel();
        int rowCount = dm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
    }
    
    private void limparCamposRmv(){
        this.campoNomeCodRmv.setText("");
        this.comboFormaAlt.setSelectedIndex(0);
        this.comboFormaPesquisa.setSelectedIndex(0);
        this.comboFormaRmv.setSelectedIndex(0);
        DefaultTableModel dm = (DefaultTableModel) this.tbFornecedorRmv.getModel();
        int rowCount = dm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
    }
    
    private void limparCamposAlt(){
        this.campoNomeCodAlt.setText("");
        this.comboFormaAlt.setSelectedIndex(0);
        this.comboFormaPesquisa.setSelectedIndex(0);
        this.comboFormaRmv.setSelectedIndex(0);
        DefaultTableModel dm = (DefaultTableModel) this.tbFornecedorAlt.getModel();
        int rowCount = dm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
    }
    
    private void listarFornecedores(int rmvPsq){
        rst=this.fornecedorController.listarFornecedores();
        DefaultTableModel model;
        switch (rmvPsq) {
            case 1:
                model = (DefaultTableModel) this.tbFornecedorRmv.getModel();
                break;
            case 2:
                model = (DefaultTableModel) this.tbFornecedor.getModel();
                break;
            default:
                model = (DefaultTableModel) this.tbFornecedorAlt.getModel();
                break;
        }
        try{
            model.addRow(new Object[]{rst.getInt("idFornecedor"),rst.getString("razaoSocial"),rst.getString("cnpj"),rst.getString("endereco"),rst.getString("tel"),rst.getString("dataCadastro"),rst.getString("outros")});
            while(rst.next()){
                model.addRow(new Object[]{rst.getInt("idFornecedor"),rst.getString("razaoSocial"),rst.getString("cnpj"),rst.getString("endereco"),rst.getString("tel"),rst.getString("dataCadastro"),rst.getString("outros")});
            }
            
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }
    
    private void btRemoverFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverFornecedorActionPerformed
        limparCamposPsq();
        limparCamposAdd();
        limparCamposAlt();
        this.listarFornecedores(1);
        this.btRmvFornecedor.setEnabled(false);
        this.btAddFornecedor.setEnabled(true);
        this.btRemoverFornecedor.setEnabled(false);
        this.btAlterarFornecedor.setEnabled(true);
        this.btConsultarFornecedor.setEnabled(true);
        this.painelAddFornecedor.setVisible(false);
        this.painelRmvFornecedor.setVisible(true);
        this.painelAltFornecedor.setVisible(false);
        this.painelPsqFornecedor.setVisible(false);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        for(int x=0;x<this.tbFornecedorRmv.getColumnCount();x++){
            this.tbFornecedorRmv.getColumnModel().getColumn(x).setCellRenderer( centerRenderer );
        }
    }//GEN-LAST:event_btRemoverFornecedorActionPerformed

    private void btAlterarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarFornecedorActionPerformed
        limparCamposPsq();
        limparCamposAdd();
        limparCamposRmv();
        this.listarFornecedores(3);
        this.btAddFornecedor.setEnabled(true);
        this.btRemoverFornecedor.setEnabled(true);
        this.btAlterarFornecedor.setEnabled(false);
        this.btConsultarFornecedor.setEnabled(true);
        this.painelAddFornecedor.setVisible(false);
        this.painelRmvFornecedor.setVisible(false);
        this.painelAltFornecedor.setVisible(true);
        this.painelPsqFornecedor.setVisible(false);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        for(int x=0;x<this.tbFornecedorAlt.getColumnCount();x++){
            this.tbFornecedorAlt.getColumnModel().getColumn(x).setCellRenderer( centerRenderer );
        }
    }//GEN-LAST:event_btAlterarFornecedorActionPerformed

    private void btConsultarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarFornecedorActionPerformed
        this.listarFornecedores(2);
        limparCamposAdd();
        limparCamposRmv();
        limparCamposAlt();
        this.btAddFornecedor.setEnabled(true);
        this.btRemoverFornecedor.setEnabled(true);
        this.btAlterarFornecedor.setEnabled(true);
        this.btConsultarFornecedor.setEnabled(false);
        this.painelAddFornecedor.setVisible(false);
        this.painelRmvFornecedor.setVisible(false);
        this.painelAltFornecedor.setVisible(false);
        this.painelPsqFornecedor.setVisible(true);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        for(int x=0;x<this.tbFornecedor.getColumnCount();x++){
            this.tbFornecedor.getColumnModel().getColumn(x).setCellRenderer( centerRenderer );
        }
    }//GEN-LAST:event_btConsultarFornecedorActionPerformed

    private void btAddFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddFornecedorActionPerformed
        limparCamposPsq();
        limparCamposRmv();
        limparCamposAlt();
        this.campoCnpjAdd.setEnabled(false);
        this.btAdicionar.setEnabled(false);
        this.btLimparAdd.setEnabled(false);
        this.btAddFornecedor.setEnabled(false);
        this.btRemoverFornecedor.setEnabled(true);
        this.btAlterarFornecedor.setEnabled(true);
        this.btConsultarFornecedor.setEnabled(true);
        this.painelAddFornecedor.setVisible(true);
        this.painelRmvFornecedor.setVisible(false);
        this.painelAltFornecedor.setVisible(false);
        this.painelPsqFornecedor.setVisible(false);
    }//GEN-LAST:event_btAddFornecedorActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        limparCamposPsq();
        limparCamposAdd();
        this.dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void campoRazaoSocialAddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoRazaoSocialAddKeyReleased
        if(this.campoRazaoSocialAdd.getText().isEmpty()){
            this.btAdicionar.setEnabled(false);
            this.campoCnpjAdd.setEnabled(false);
            this.campoTelAdd.setEnabled(false);
        }
        else if(!this.campoCnpjAdd.getText().contains(" ")&&!this.campoTelAdd.getText().contains(" ")){
            this.campoCnpjAdd.setEnabled(true);
            this.campoTelAdd.setEnabled(true);
            this.btAdicionar.setEnabled(true);
        }
        else if(!this.campoCnpjAdd.getText().contains(" ")){
            this.campoCnpjAdd.setEnabled(true);
        }
        else{
            this.btLimparAdd.setEnabled(true);
            this.campoCnpjAdd.setEnabled(true);
        }
    }//GEN-LAST:event_campoRazaoSocialAddKeyReleased

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        try{
            if(!this.fornecedorController.cnpjExistente(this.campoCnpjAdd.getText())){
                String endereco = this.campoEnderecoAdd.getText() + this.campoNumAdd.getText() + this.campoComplementoAdd.getText()+
                this.campoBairroAdd.getText()+this.campoCidadeAdd.getText()+this.comboUf.getSelectedItem();
                this.fornecedorController.adicionarFornecedor(this.campoRazaoSocialAdd.getText(), this.campoCnpjAdd.getText(), endereco ,
                    this.campoTelAdd.getText(), this.campoDescricaoAdd.getText());
                JOptionPane.showMessageDialog(null,"Fornecedor adicionado com sucesso!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null,"CNPJ já cadastrado no sistema!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(HeadlessException e){
            JOptionPane.showMessageDialog(null,"Preencha os campos corretamente!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
        }
        limparCamposAdd();
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btLimparAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparAddActionPerformed
        limparCamposAdd();
        this.campoCnpjAdd.setEnabled(false);
        this.campoTelAdd.setEnabled(false);
        this.btLimparAdd.setEnabled(false);
        this.btAdicionar.setEnabled(false);
    }//GEN-LAST:event_btLimparAddActionPerformed

    private void campoBairroAddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBairroAddKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBairroAddKeyReleased

    private void comboFormaRmvItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFormaRmvItemStateChanged
        this.campoNomeCodRmv.setText("");
        DefaultTableModel dm = (DefaultTableModel) this.tbFornecedorRmv.getModel();
        switch (this.comboFormaRmv.getSelectedIndex()) {
            case 0:
                this.campoNomeCodRmv.setEnabled(false);
                this.lbFormaPesquisaRmv.setText("Todos Fornecedores");
                if(cont==0){
                    this.listarFornecedores(1);
                    cont++;
                }   this.btRmvFornecedor.setEnabled(false);
                break;
            case 1:
                {
                    int rowCount = dm.getRowCount();
                    for (int i = rowCount - 1; i >= 0; i--) {
                        dm.removeRow(i);
                    }       this.campoNomeCodRmv.setEnabled(true);
                    this.lbFormaPesquisaRmv.setText("Razão social do fornecedor");
                    cont=0;
                    this.btRmvFornecedor.setEnabled(false);
                    break;
                }
            default:
                {
                    int rowCount = dm.getRowCount();
                    for (int i = rowCount - 1; i >= 0; i--) {
                        dm.removeRow(i);
                    }       this.campoNomeCodRmv.setEnabled(true);
                    this.lbFormaPesquisaRmv.setText("Código do fornecedor");
                    cont=0;
                    this.btRmvFornecedor.setEnabled(false);
                    break;
                }
        }
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        for(int x=0;x<this.tbFornecedorRmv.getColumnCount();x++){
            this.tbFornecedorRmv.getColumnModel().getColumn(x).setCellRenderer( centerRenderer );
        }
    }//GEN-LAST:event_comboFormaRmvItemStateChanged

    private void btBuscarRmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarRmvActionPerformed
        DefaultTableModel dm = (DefaultTableModel) this.tbFornecedorRmv.getModel();
        if(this.comboFormaRmv.getSelectedIndex()==0&&this.tbFornecedorRmv.getRowCount()<0){
            this.listarFornecedores(1);
        }
        else if(this.comboFormaRmv.getSelectedIndex()==1&&!this.campoNomeCodRmv.getText().isEmpty()){
            int rowCount = dm.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) {
                dm.removeRow(i);
            }
            rst=this.fornecedorController.buscarFornecedor(this.campoNomeCodRmv.getText(), 0);
            DefaultTableModel model = (DefaultTableModel) this.tbFornecedorRmv.getModel();
            try{
                model.addRow(new Object[]{rst.getInt("idFornecedor"),rst.getString("razaoSocial"),rst.getString("cnpj"),rst.getString("endereco"),rst.getString("tel"),rst.getString("dataCadastro"),rst.getString("outros")});
                while(rst.next()){
                    model.addRow(new Object[]{rst.getInt("idFornecedor"),rst.getString("razaoSocial"),rst.getString("cnpj"),rst.getString("endereco"),rst.getString("tel"),rst.getString("dataCadastro"),rst.getString("outros")});
                }
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Não foi encontrado nenhum fornecedor com essa razão social!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else if(this.comboFormaRmv.getSelectedIndex()==2&&!this.campoNomeCodRmv.getText().isEmpty()){
            int rowCount = dm.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) {
                dm.removeRow(i);
            }
            rst=this.fornecedorController.buscarFornecedor("null", Integer.parseInt(this.campoNomeCodRmv.getText()));
            DefaultTableModel model = (DefaultTableModel) this.tbFornecedorRmv.getModel();
            try{
                model.addRow(new Object[]{rst.getInt("idFornecedor"),rst.getString("razaoSocial"),rst.getString("cnpj"),rst.getString("endereco"),rst.getString("tel"),rst.getString("dataCadastro"),rst.getString("outros")});
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Não foi encontrado nenhum fornecedor com esse código!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        for(int x=0;x<this.tbFornecedorRmv.getColumnCount();x++){
            this.tbFornecedorRmv.getColumnModel().getColumn(x).setCellRenderer( centerRenderer );
        }
    }//GEN-LAST:event_btBuscarRmvActionPerformed

    private void tbFornecedorRmvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFornecedorRmvMouseClicked
        if(this.tbFornecedorRmv.getSelectedRowCount()>0){
            this.btRmvFornecedor.setEnabled(true);
        }
        else{
            this.btRmvFornecedor.setEnabled(false);
        }
    }//GEN-LAST:event_tbFornecedorRmvMouseClicked

    private void btRmvFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRmvFornecedorActionPerformed
        if(tbFornecedorRmv.getSelectedRowCount()>=1){
            this.msgConfirmaRmv.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"Selecione um fornecedor!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btRmvFornecedorActionPerformed

    private void comboFormaAltItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFormaAltItemStateChanged
        this.campoNomeCodAlt.setText("");
        DefaultTableModel dm = (DefaultTableModel) this.tbFornecedorAlt.getModel();
        switch (this.comboFormaAlt.getSelectedIndex()) {
            case 0:
                this.campoNomeCodAlt.setEnabled(false);
                this.lbFormaPesquisaAlt.setText("Todos fornecedores");
                if(cont==0){
                    this.listarFornecedores(3);
                    cont++;
                }   this.btRmvFornecedor.setEnabled(false);
                break;
            case 1:
                {
                    int rowCount = dm.getRowCount();
                    for (int i = rowCount - 1; i >= 0; i--) {
                        dm.removeRow(i);
                    }       this.campoNomeCodAlt.setEnabled(true);
                    this.lbFormaPesquisaAlt.setText("Razão social do fornecedor");
                    cont=0;
                    this.btRmvFornecedor.setEnabled(false);
                    break;
                }
            default:
                {
                    int rowCount = dm.getRowCount();
                    for (int i = rowCount - 1; i >= 0; i--) {
                        dm.removeRow(i);
                    }       this.campoNomeCodAlt.setEnabled(true);
                    this.lbFormaPesquisaAlt.setText("Código do fornecedor");
                    cont=0;
                    this.btRmvFornecedor.setEnabled(false);
                    break;
                }
        }
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        for(int x=0;x<this.tbFornecedorAlt.getColumnCount();x++){
            this.tbFornecedorAlt.getColumnModel().getColumn(x).setCellRenderer( centerRenderer );
        }
    }//GEN-LAST:event_comboFormaAltItemStateChanged

    private void btBuscarAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarAltActionPerformed
        DefaultTableModel dm = (DefaultTableModel) this.tbFornecedorAlt.getModel();
        if(this.comboFormaAlt.getSelectedIndex()==0&&this.tbFornecedorAlt.getRowCount()<0){
            this.listarFornecedores(1);
        }
        else if(this.comboFormaAlt.getSelectedIndex()==1&&!this.campoNomeCodAlt.getText().isEmpty()){
            int rowCount = dm.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) {
                dm.removeRow(i);
            }
            rst=this.fornecedorController.buscarFornecedor(this.campoNomeCodAlt.getText(), 0);
            DefaultTableModel model = (DefaultTableModel) this.tbFornecedorAlt.getModel();
            try{
                model.addRow(new Object[]{rst.getInt("idFornecedor"),rst.getString("razaoSocial"),rst.getString("cnpj"),rst.getString("endereco"),rst.getString("tel"),rst.getString("dataCadastro"),rst.getString("outros")});
                while(rst.next()){
                    model.addRow(new Object[]{rst.getInt("idFornecedor"),rst.getString("razaoSocial"),rst.getString("cnpj"),rst.getString("endereco"),rst.getString("tel"),rst.getString("dataCadastro"),rst.getString("outros")});
                }
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Não foi encontrado nenhum fornecedor com essa razão social!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else if(this.comboFormaAlt.getSelectedIndex()==2&&!this.campoNomeCodAlt.getText().isEmpty()){
            int rowCount = dm.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) {
                dm.removeRow(i);
            }
            rst=this.fornecedorController.buscarFornecedor("null", Integer.parseInt(this.campoNomeCodAlt.getText()));
            DefaultTableModel model = (DefaultTableModel) this.tbFornecedorAlt.getModel();
            try{
                model.addRow(new Object[]{rst.getInt("idFornecedor"),rst.getString("razaoSocial"),rst.getString("cnpj"),rst.getString("endereco"),rst.getString("tel"),rst.getString("dataCadastro"),rst.getString("outros")});
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Não foi encontrado nenhum fornecedor com esse código!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        for(int x=0;x<this.tbFornecedorAlt.getColumnCount();x++){
            this.tbFornecedorAlt.getColumnModel().getColumn(x).setCellRenderer( centerRenderer );
        }
    }//GEN-LAST:event_btBuscarAltActionPerformed

    private void tbFornecedorAltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFornecedorAltMouseClicked
        if(this.tbFornecedorAlt.getSelectedRow()>=0){
            nomeAntigo = String.valueOf(this.tbFornecedorAlt.getValueAt(this.tbFornecedorAlt.getSelectedRow(), 1));
            cnpjAntigo = String.valueOf(this.tbFornecedorAlt.getValueAt(this.tbFornecedorAlt.getSelectedRow(), 2));
            enderecoAntigo = String.valueOf(this.tbFornecedorAlt.getValueAt(this.tbFornecedorAlt.getSelectedRow(), 3));
            telAntigo = String.valueOf(this.tbFornecedorAlt.getValueAt(this.tbFornecedorAlt.getSelectedRow(), 4));
            outrosAntigo = String.valueOf(this.tbFornecedorAlt.getValueAt(this.tbFornecedorAlt.getSelectedRow(), 6));
        }
    }//GEN-LAST:event_tbFornecedorAltMouseClicked

    private void tbFornecedorAltPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbFornecedorAltPropertyChange
        if(this.tbFornecedorAlt.getSelectedRow()>=0){
            if(!String.valueOf(this.tbFornecedorAlt.getValueAt(this.tbFornecedorAlt.getSelectedRow(), 1)).equals(nomeAntigo)||
                !String.valueOf(this.tbFornecedorAlt.getValueAt(this.tbFornecedorAlt.getSelectedRow(), 1)).equals(cnpjAntigo)||
                !String.valueOf(this.tbFornecedorAlt.getValueAt(this.tbFornecedorAlt.getSelectedRow(), 1)).equals(enderecoAntigo)||
                !String.valueOf(this.tbFornecedorAlt.getValueAt(this.tbFornecedorAlt.getSelectedRow(), 5)).equals(telAntigo)||
                !String.valueOf(this.tbFornecedorAlt.getValueAt(this.tbFornecedorAlt.getSelectedRow(), 6)).equals(outrosAntigo))
            {
                this.fornecedorController.alterarFornecedor((Integer) this.tbFornecedorAlt.getValueAt(this.tbFornecedorAlt.getSelectedRow(), 0),
                    String.valueOf(this.tbFornecedorAlt.getValueAt(this.tbFornecedorAlt.getSelectedRow(), 1)),
                    String.valueOf(this.tbFornecedorAlt.getValueAt(this.tbFornecedorAlt.getSelectedRow(), 2)),
                    String.valueOf(this.tbFornecedorAlt.getValueAt(this.tbFornecedorAlt.getSelectedRow(), 3)),
                    String.valueOf(this.tbFornecedorAlt.getValueAt(this.tbFornecedorAlt.getSelectedRow(), 4)),
                    String.valueOf(this.tbFornecedorAlt.getValueAt(this.tbFornecedorAlt.getSelectedRow(), 6))
                );
            }
        }
    }//GEN-LAST:event_tbFornecedorAltPropertyChange

    private void btBuscarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarFornecedorActionPerformed
        DefaultTableModel dm = (DefaultTableModel) this.tbFornecedor.getModel();
        if(this.comboFormaPesquisa.getSelectedIndex()==0&&this.tbFornecedor.getRowCount()<0){
            this.listarFornecedores(2);
        }
        else if(this.comboFormaPesquisa.getSelectedIndex()==1&&!this.campoNomeCod.getText().isEmpty()){
            int rowCount = dm.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) {
                dm.removeRow(i);
            }
            rst=this.fornecedorController.buscarFornecedor(this.campoNomeCod.getText(), 0);
            DefaultTableModel model = (DefaultTableModel) this.tbFornecedor.getModel();
            try{
                model.addRow(new Object[]{rst.getInt("idFornecedor"),rst.getString("razaoSocial"),rst.getString("cnpj"),rst.getString("endereco"),rst.getString("tel"),rst.getString("dataCadastro"),rst.getString("outros")});
                while(rst.next()){
                    model.addRow(new Object[]{rst.getInt("idFornecedor"),rst.getString("razaoSocial"),rst.getString("cnpj"),rst.getString("endereco"),rst.getString("tel"),rst.getString("dataCadastro"),rst.getString("outros")});
                }
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Não foi encontrado nenhum fornecedor com essa razão social!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else if(this.comboFormaPesquisa.getSelectedIndex()==2&&!this.campoNomeCod.getText().isEmpty()){
            int rowCount = dm.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) {
                dm.removeRow(i);
            }
            rst=this.fornecedorController.buscarFornecedor("null", Integer.parseInt(this.campoNomeCod.getText()));
            DefaultTableModel model = (DefaultTableModel) this.tbFornecedor.getModel();
            try{
                model.addRow(new Object[]{rst.getInt("idFornecedor"),rst.getString("razaoSocial"),rst.getString("cnpj"),rst.getString("endereco"),rst.getString("tel"),rst.getString("dataCadastro"),rst.getString("outros")});
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Não foi encontrado nenhum fornecedor com esse código!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        for(int x=0;x<this.tbFornecedor.getColumnCount();x++){
            this.tbFornecedor.getColumnModel().getColumn(x).setCellRenderer( centerRenderer );
        }
    }//GEN-LAST:event_btBuscarFornecedorActionPerformed

    private void comboFormaPesquisaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFormaPesquisaItemStateChanged
        this.campoNomeCod.setText("");
        DefaultTableModel dm = (DefaultTableModel) this.tbFornecedor.getModel();
        switch (this.comboFormaPesquisa.getSelectedIndex()) {
            case 0:
                this.campoNomeCod.setEnabled(false);
                this.lbFormaPesquisa.setText("Todos fornecedores");
                if(cont==0){
                    this.listarFornecedores(2);
                    cont++;
                }   break;
            case 1:
                {
                    int rowCount = dm.getRowCount();
                    for (int i = rowCount - 1; i >= 0; i--) {
                        dm.removeRow(i);
                    }       this.campoNomeCod.setEnabled(true);
                    this.lbFormaPesquisa.setText("Razão social do fornecedor");
                    cont=0;
                    break;
                }
            default:
                {
                    int rowCount = dm.getRowCount();
                    for (int i = rowCount - 1; i >= 0; i--) {
                        dm.removeRow(i);
                    }       this.campoNomeCod.setEnabled(true);
                    this.lbFormaPesquisa.setText("Código do fornecedor");
                    cont=0;
                    break;
                }
        }
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        for(int x=0;x<this.tbFornecedor.getColumnCount();x++){
            this.tbFornecedor.getColumnModel().getColumn(x).setCellRenderer( centerRenderer );
        }
    }//GEN-LAST:event_comboFormaPesquisaItemStateChanged

    private void btSimRmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimRmvActionPerformed
        this.fornecedorController.removerFornecedor((Integer)this.tbFornecedorRmv.getValueAt(this.tbFornecedorRmv.getSelectedRow(),0));
        DefaultTableModel dm = (DefaultTableModel) this.tbFornecedorRmv.getModel();
        if(this.comboFormaRmv.getSelectedIndex()==0){
            int rowCount = dm.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) {
                dm.removeRow(i);
            }
            this.listarFornecedores(1);
        }
        else{
            int rowCount = dm.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) {
                dm.removeRow(i);
            }
        }
        JOptionPane.showMessageDialog(null,"Fornecedor removido com sucesso!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
        msgConfirmaRmv.dispose();
    }//GEN-LAST:event_btSimRmvActionPerformed

    private void btNaoRmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNaoRmvActionPerformed
        msgConfirmaRmv.dispose();
    }//GEN-LAST:event_btNaoRmvActionPerformed

    private void campoCnpjAddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCnpjAddKeyReleased
        if(this.campoCnpjAdd.getText().contains(" ")){
            this.btAdicionar.setEnabled(false);
            this.campoTelAdd.setEnabled(false);
        }
        else if(!this.campoTelAdd.getText().contains(" ")){
            this.campoTelAdd.setEnabled(true);
            this.btAdicionar.setEnabled(true);
        }
        else{
            this.campoTelAdd.setEnabled(true);
        }
    }//GEN-LAST:event_campoCnpjAddKeyReleased

    private void campoTelAddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTelAddKeyReleased
        if(this.campoTelAdd.getText().isEmpty()){
            this.btAdicionar.setEnabled(false);
        }
        else if(!this.campoTelAdd.getText().contains(" ")){
            this.btAdicionar.setEnabled(true);
        }
        else{
            this.btAdicionar.setEnabled(false);
        }
    }//GEN-LAST:event_campoTelAddKeyReleased

    private void campoEnderecoAddKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoEnderecoAddKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c == evt.VK_SPACE ||  c==evt.VK_DELETE ))
            evt.consume();
    }//GEN-LAST:event_campoEnderecoAddKeyTyped

    private void campoBairroAddKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBairroAddKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c == evt.VK_SPACE ||  c==evt.VK_DELETE ))
            evt.consume();
    }//GEN-LAST:event_campoBairroAddKeyTyped

    private void campoCidadeAddKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCidadeAddKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c == evt.VK_SPACE ||  c==evt.VK_DELETE ))
            evt.consume();
    }//GEN-LAST:event_campoCidadeAddKeyTyped

    private void campoNumAddKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNumAddKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_campoNumAddKeyTyped

    private void campoNomeCodRmvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomeCodRmvKeyTyped
        char c = evt.getKeyChar();
        if(this.lbFormaPesquisaRmv.getText().equals("Razão social do fornecedor")){
            if(!(Character.isAlphabetic(c) || c == evt.VK_SPACE ||  c==evt.VK_DELETE ))
                evt.consume();
        }
        else if(this.lbFormaPesquisaRmv.getText().equals("Código do fornecedor")){
            if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_campoNomeCodRmvKeyTyped

    private void campoNomeCodAltKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomeCodAltKeyTyped
        char c = evt.getKeyChar();
        if(this.lbFormaPesquisaAlt.getText().equals("Razão social do fornecedor")){
            if(!(Character.isAlphabetic(c) || c == evt.VK_SPACE ||  c==evt.VK_DELETE ))
                evt.consume();
        }
        else if(this.lbFormaPesquisaAlt.getText().equals("Código do fornecedor")){
            if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_campoNomeCodAltKeyTyped

    private void campoNomeCodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomeCodKeyTyped
        char c = evt.getKeyChar();
        if(this.lbFormaPesquisa.getText().equals("Razão social do fornecedor")){
            if(!(Character.isAlphabetic(c) || c == evt.VK_SPACE ||  c==evt.VK_DELETE ))
                evt.consume();
        }
        else if(this.lbFormaPesquisa.getText().equals("Código do fornecedor")){
            if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_campoNomeCodKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InterfaceFornecedor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddFornecedor;
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btAlterarFornecedor;
    private javax.swing.JButton btBuscarAlt;
    private javax.swing.JButton btBuscarFornecedor;
    private javax.swing.JButton btBuscarRmv;
    private javax.swing.JButton btConsultarFornecedor;
    private javax.swing.JButton btLimparAdd;
    private javax.swing.JButton btNaoRmv;
    private javax.swing.JButton btRemoverFornecedor;
    private javax.swing.JButton btRmvFornecedor;
    private javax.swing.JButton btSimRmv;
    private javax.swing.JButton btVoltar;
    private javax.swing.JTextField campoBairroAdd;
    private javax.swing.JTextField campoCidadeAdd;
    private javax.swing.JFormattedTextField campoCnpjAdd;
    private javax.swing.JTextField campoComplementoAdd;
    private javax.swing.JTextArea campoDescricaoAdd;
    private javax.swing.JTextField campoEnderecoAdd;
    private javax.swing.JTextField campoNomeCod;
    private javax.swing.JTextField campoNomeCodAlt;
    private javax.swing.JTextField campoNomeCodRmv;
    private javax.swing.JTextField campoNumAdd;
    private javax.swing.JTextField campoRazaoSocialAdd;
    private javax.swing.JFormattedTextField campoTelAdd;
    private javax.swing.JComboBox<String> comboFormaAlt;
    private javax.swing.JComboBox<String> comboFormaPesquisa;
    private javax.swing.JComboBox<String> comboFormaRmv;
    private javax.swing.JComboBox<String> comboUf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbFormaPesquisa;
    private javax.swing.JLabel lbFormaPesquisaAlt;
    private javax.swing.JLabel lbFormaPesquisaRmv;
    private javax.swing.JDialog msgConfirmaRmv;
    private javax.swing.JPanel painelAddFornecedor;
    private javax.swing.JPanel painelAltFornecedor;
    private javax.swing.JLayeredPane painelCamadaFornecedor;
    private javax.swing.JPanel painelFornecedor;
    private javax.swing.JPanel painelPsqFornecedor;
    private javax.swing.JPanel painelRmvFornecedor;
    private javax.swing.JPanel painelSair;
    private javax.swing.JTable tbFornecedor;
    private javax.swing.JTable tbFornecedorAlt;
    private javax.swing.JTable tbFornecedorRmv;
    // End of variables declaration//GEN-END:variables
}
