/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.VendaController;
import java.awt.Image;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Controller.InicializacaoController;
import com.sun.glass.events.KeyEvent;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JLabel;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author Pedro
 */
public class InterfacePrincipal extends javax.swing.JFrame {
    private VendaController vendaController=new VendaController();
    private ResultSet rst;
    private int cont=0;
    private float total=0;
    private float totalGeral=0;
    private InicializacaoController inicializar;
    private static final String COMMIT_ACTION = "commit";
    DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    Date today = Calendar.getInstance().getTime();  
    String reportDate = df.format(today);
    String nomeCompleto;
    String numVenda;
    String usuario;
    boolean permissao;
    URL url = this.getClass().getResource("/Imagens/Icone.png");  
    Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
    int quantidadeAntiga=0;
    /**
     * Creates new form InterfacePrincipal
     */
    public InterfacePrincipal(String usuario,String nome, boolean permissao) {
        this.usuario=usuario;
        inicializar = new InicializacaoController(this.usuario);
        rst=inicializar.inicializacao.getRst();
        try{
            this.nomeCompleto=nome;
            this.numVenda=String.valueOf(rst.getInt("count(idVenda)")+1);
            this.permissao=permissao;
        }
        catch(Exception e){}
        
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setUndecorated(true);
        initComponents();
        tabelaModificada();
    }

    private InterfacePrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgSair = new javax.swing.JDialog();
        painelSair = new javax.swing.JPanel();
        btSim = new javax.swing.JButton();
        btNao = new javax.swing.JButton();
        painelPrincipal = new javax.swing.JPanel();
        btGerProduto = new javax.swing.JButton();
        btGerFornecedor = new javax.swing.JButton();
        btGerUsuario = new javax.swing.JButton();
        btGerRelatorio = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        painelVendas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbNumVenda = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbFuncionario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoVendaQuantidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoVendaProduto = new javax.swing.JTextField();
        btAddProduto = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbVenda = new javax.swing.JTable();
        btFinalizarVenda = new javax.swing.JButton();
        btDeletarVenda = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        campoCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoDesconto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboPagamento = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        campoRecebido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbDesconto = new javax.swing.JLabel();
        lbTotalGeral = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        radioImprimir = new javax.swing.JRadioButton();
        radioNaoImprimir = new javax.swing.JRadioButton();
        btDesconto = new javax.swing.JButton();
        btAlternar = new javax.swing.JButton();
        btGerCliente = new javax.swing.JButton();
        menuPrincipal = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuSair = new javax.swing.JMenuItem();
        mnProduto = new javax.swing.JMenu();
        mnFornecedore = new javax.swing.JMenu();
        mnUsuario = new javax.swing.JMenu();
        mnRelatorio = new javax.swing.JMenu();
        menuAjuda = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuSobre = new javax.swing.JMenuItem();

        msgSair.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        msgSair.setTitle("Deseja realmente sair?");
        msgSair.setAlwaysOnTop(true);
        msgSair.setIconImage(iconeTitulo);
        msgSair.setLocation(new java.awt.Point(500, 250));
        msgSair.setMinimumSize(new java.awt.Dimension(190, 70));
        msgSair.setResizable(false);

        painelSair.setPreferredSize(new java.awt.Dimension(45, 45));

        btSim.setText("Sim");
        btSim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimActionPerformed(evt);
            }
        });

        btNao.setText("Não");
        btNao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelSairLayout = new javax.swing.GroupLayout(painelSair);
        painelSair.setLayout(painelSairLayout);
        painelSairLayout.setHorizontalGroup(
            painelSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSairLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btSim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addComponent(btNao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        painelSairLayout.setVerticalGroup(
            painelSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSairLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSim)
                    .addComponent(btNao))
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout msgSairLayout = new javax.swing.GroupLayout(msgSair.getContentPane());
        msgSair.getContentPane().setLayout(msgSairLayout);
        msgSairLayout.setHorizontalGroup(
            msgSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelSair, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        msgSairLayout.setVerticalGroup(
            msgSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelSair, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Goma Café Com Tabaco @ User: "+ this.usuario);
        setIconImage(iconeTitulo);

        btGerProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Produtos.png"))); // NOI18N
        btGerProduto.setText("Produtos");
        btGerProduto.setToolTipText("Gerenciar produtos");
        btGerProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));
        btGerProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btGerProduto.setMaximumSize(new java.awt.Dimension(389, 265));
        btGerProduto.setMinimumSize(new java.awt.Dimension(389, 265));
        btGerProduto.setPreferredSize(new java.awt.Dimension(320, 265));
        btGerProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerProdutoActionPerformed(evt);
            }
        });

        btGerFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Fornecedores.png"))); // NOI18N
        btGerFornecedor.setText("Fornecedores");
        btGerFornecedor.setToolTipText("Gerenciar fornecedores");
        btGerFornecedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));
        btGerFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btGerFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerFornecedorActionPerformed(evt);
            }
        });

        btGerUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Usuarios.png"))); // NOI18N
        btGerUsuario.setText("Usuários");
        btGerUsuario.setToolTipText("Gerenciar usuários");
        btGerUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));
        btGerUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btGerUsuario.setMaximumSize(new java.awt.Dimension(389, 265));
        btGerUsuario.setMinimumSize(new java.awt.Dimension(389, 265));
        btGerUsuario.setPreferredSize(new java.awt.Dimension(389, 265));
        btGerUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerUsuarioActionPerformed(evt);
            }
        });

        btGerRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Gerenciamento.png"))); // NOI18N
        btGerRelatorio.setText("Relatório financeiro");
        btGerRelatorio.setToolTipText("Gerenciar relatórios");
        btGerRelatorio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));
        btGerRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btGerRelatorio.setMaximumSize(new java.awt.Dimension(389, 265));
        btGerRelatorio.setMinimumSize(new java.awt.Dimension(389, 265));
        btGerRelatorio.setPreferredSize(new java.awt.Dimension(389, 265));
        btGerRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerRelatorioActionPerformed(evt);
            }
        });

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair.png"))); // NOI18N
        btSair.setToolTipText("Sair");
        btSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        painelVendas.setBackground(new java.awt.Color(250, 250, 250));
        painelVendas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Venda nº");
        jLabel1.setToolTipText("Número de vendas do dia");

        lbNumVenda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbNumVenda.setForeground(new java.awt.Color(0, 102, 102));
        lbNumVenda.setText(this.numVenda);
        lbNumVenda.setToolTipText("Número de vendas do dia");
        lbNumVenda.setName("lbNumVenda"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Funcionário: ");

        lbFuncionario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbFuncionario.setText(this.nomeCompleto);
        lbFuncionario.setToolTipText("Funcionário ativo no sistema");
        lbFuncionario.setName("lbFuncionario"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Data:");

        lbData.setText(reportDate);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Quantidade:");

        campoVendaQuantidade.setToolTipText("Quantidade do produto a ser adicionado ao carrinho");
        campoVendaQuantidade.setEnabled(false);
        campoVendaQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoVendaQuantidadeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoVendaQuantidadeKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Produto:");

        campoVendaProduto.setToolTipText("Produto a ser adicionado ao carrinho");
        campoVendaProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoVendaProdutoKeyReleased(evt);
            }
        });

        btAddProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Adicionar.png"))); // NOI18N
        btAddProduto.setText("Adicionar");
        btAddProduto.setToolTipText("Adicionar produto ao carrinho");
        btAddProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAddProduto.setEnabled(false);
        btAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddProdutoActionPerformed(evt);
            }
        });

        btRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/remover.png"))); // NOI18N
        btRemover.setToolTipText("Remover produto selecionado");
        btRemover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRemover.setEnabled(false);
        btRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRemoverMouseClicked(evt);
            }
        });
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        tbVenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Quantidade", "Preço unitário", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbVenda.setToolTipText("Lista de produtos no carrinho");
        tbVenda.getTableHeader().setReorderingAllowed(false);
        tbVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbVendaMouseClicked(evt);
            }
        });
        tbVenda.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbVendaPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(tbVenda);

        btFinalizarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Finalizar.png"))); // NOI18N
        btFinalizarVenda.setText("Concluir venda");
        btFinalizarVenda.setToolTipText("Concluir venda");
        btFinalizarVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFinalizarVenda.setEnabled(false);
        btFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalizarVendaActionPerformed(evt);
            }
        });

        btDeletarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Deletar.png"))); // NOI18N
        btDeletarVenda.setText("Limpar carrinho");
        btDeletarVenda.setToolTipText("Limpar carrinho");
        btDeletarVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDeletarVenda.setEnabled(false);
        btDeletarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarVendaActionPerformed(evt);
            }
        });

        jLabel6.setText("Cliente (opcional):");

        campoCliente.setToolTipText("");
        campoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoClienteKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Desconto:");

        campoDesconto.setToolTipText("Desconto na venda");
        campoDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoDescontoKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Forma de pagamento:");

        comboPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão", "A prazo" }));
        comboPagamento.setToolTipText("Selecione a forma de pagamento");
        comboPagamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Valor recebido:");

        campoRecebido.setToolTipText("Valor recebido pelo cliente");
        campoRecebido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRecebidoActionPerformed(evt);
            }
        });
        campoRecebido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoRecebidoKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Total:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Desconto:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Total geral:");

        lbDesconto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbDesconto.setText("0");
        lbDesconto.setToolTipText("Desconto efetuado");

        lbTotalGeral.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTotalGeral.setText("0");
        lbTotalGeral.setToolTipText("Valor total após desconto");

        lbTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTotal.setText("0");
        lbTotal.setToolTipText("Valor total presente no carrinho");

        jLabel13.setText("Imprimir?");
        jLabel13.setToolTipText("Impressão do relatório de venda");

        radioImprimir.setText("Sim");
        radioImprimir.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioImprimirStateChanged(evt);
            }
        });
        radioImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioImprimirMouseClicked(evt);
            }
        });

        radioNaoImprimir.setSelected(true);
        radioNaoImprimir.setText("Não");
        radioNaoImprimir.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioNaoImprimirStateChanged(evt);
            }
        });
        radioNaoImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioNaoImprimirMouseClicked(evt);
            }
        });

        btDesconto.setText("OK");
        btDesconto.setToolTipText("Confirmar desconto na venda");
        btDesconto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDesconto.setEnabled(false);
        btDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDescontoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelVendasLayout = new javax.swing.GroupLayout(painelVendas);
        painelVendas.setLayout(painelVendasLayout);
        painelVendasLayout.setHorizontalGroup(
            painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelVendasLayout.createSequentialGroup()
                .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelVendasLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelVendasLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbNumVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelVendasLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoVendaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(127, 127, 127)
                        .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelVendasLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(painelVendasLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoVendaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(51, 51, 51)
                        .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelVendasLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelVendasLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(btAddProduto))))
                    .addGroup(painelVendasLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(painelVendasLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelVendasLayout.createSequentialGroup()
                                        .addGap(101, 101, 101)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radioNaoImprimir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radioImprimir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btDeletarVenda)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btFinalizarVenda))
                                    .addGroup(painelVendasLayout.createSequentialGroup()
                                        .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(painelVendasLayout.createSequentialGroup()
                                                .addComponent(campoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(117, 117, 117)
                                                .addComponent(jLabel7))
                                            .addGroup(painelVendasLayout.createSequentialGroup()
                                                .addComponent(comboPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel9)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(campoDesconto)
                                            .addComponent(campoRecebido, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btDesconto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbDesconto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbTotalGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(54, 54, 54)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRemover)
                .addContainerGap())
        );
        painelVendasLayout.setVerticalGroup(
            painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbNumVenda)
                    .addComponent(jLabel2)
                    .addComponent(lbFuncionario)
                    .addComponent(jLabel3)
                    .addComponent(lbData))
                .addGap(43, 43, 43)
                .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoVendaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(campoVendaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAddProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(campoDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDesconto))
                .addGap(2, 2, 2)
                .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lbDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelVendasLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(comboPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(campoRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelVendasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTotalGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btDeletarVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btFinalizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(radioImprimir)
                        .addComponent(radioNaoImprimir)))
                .addContainerGap())
        );

        lbNumVenda.getAccessibleContext().setAccessibleName("lbNumVenda");
        lbFuncionario.getAccessibleContext().setAccessibleName("lbFuncionario");

        btAlternar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/AlternarUsuario.png"))); // NOI18N
        btAlternar.setToolTipText("Mudar de usuário");
        btAlternar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAlternar.setMinimumSize(new java.awt.Dimension(109, 41));
        btAlternar.setPreferredSize(new java.awt.Dimension(109, 41));
        btAlternar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlternarActionPerformed(evt);
            }
        });

        btGerCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Clientes.png"))); // NOI18N
        btGerCliente.setText("Clientes");
        btGerCliente.setToolTipText("Gerenciar fornecedores");
        btGerCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));
        btGerCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btGerCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(painelVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 970, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                        .addComponent(btGerProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 154, Short.MAX_VALUE)
                        .addGap(50, 50, 50)
                        .addComponent(btGerCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addGap(50, 50, 50)
                        .addComponent(btGerFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addGap(50, 50, 50)
                        .addComponent(btGerUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 154, Short.MAX_VALUE)
                        .addGap(50, 50, 50)
                        .addComponent(btGerRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 154, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                        .addComponent(btAlternar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGerProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGerFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGerUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGerRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGerCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAlternar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(3, 3, 3))
        );

        menuArquivo.setText("Arquivo");
        menuArquivo.add(jSeparator2);

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuSair);

        menuPrincipal.add(menuArquivo);

        mnProduto.setText("Produtos");
        menuPrincipal.add(mnProduto);

        mnFornecedore.setText("Fornecedores");
        menuPrincipal.add(mnFornecedore);

        mnUsuario.setText("Usuários");
        menuPrincipal.add(mnUsuario);

        mnRelatorio.setText("Relatórios");
        menuPrincipal.add(mnRelatorio);

        menuAjuda.setText("Ajuda");
        menuAjuda.add(jSeparator3);

        menuSobre.setText("Sobre");
        menuAjuda.add(menuSobre);

        menuPrincipal.add(menuAjuda);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGerProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerProdutoActionPerformed
        if(this.permissao){
            InterfaceProduto interfaceProduto = new InterfaceProduto();
            interfaceProduto.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"Você não tem permissão para entrar nessa área!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btGerProdutoActionPerformed

    private void btGerFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerFornecedorActionPerformed
        if(this.permissao){
            InterfaceFornecedor interfaceFornecedor = new InterfaceFornecedor();
            interfaceFornecedor.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"Você não tem permissão para entrar nessa área!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btGerFornecedorActionPerformed

    private void btGerUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerUsuarioActionPerformed
        if(this.permissao){
            InterfaceUsuario interfaceUsuario = new InterfaceUsuario();
            interfaceUsuario.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"Você não tem permissão para entrar nessa área!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btGerUsuarioActionPerformed

    private void btGerRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGerRelatorioActionPerformed
    
    private void tabelaModificada(){
        this.tbVenda.getModel().addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                if(tbVenda.getRowCount()>=1){
                    btDesconto.setEnabled(true);
                    btDeletarVenda.setEnabled(true);
                    btFinalizarVenda.setEnabled(true);
                }
                else{
                    btDesconto.setEnabled(false);
                    btDeletarVenda.setEnabled(false);
                    btFinalizarVenda.setEnabled(false);
                }
            }
        });
    }
    
    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        msgSair.setVisible(true);
    }//GEN-LAST:event_btSairActionPerformed

    private void btSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimActionPerformed
        voltarListaEstoque();
        this.reiniciarCampos();
        System.exit(0);
    }//GEN-LAST:event_btSimActionPerformed

    private void btNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNaoActionPerformed
        msgSair.dispose();
    }//GEN-LAST:event_btNaoActionPerformed

    private void btAlternarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlternarActionPerformed
        voltarListaEstoque();
        this.reiniciarCampos();
        InterfaceLogin interfaceLogin = new InterfaceLogin();
        interfaceLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btAlternarActionPerformed

    private void btDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDescontoActionPerformed
        try{
            if(this.lbDesconto.getText().isEmpty()){
                this.lbDesconto.setText(this.campoDesconto.getText());
            }
            else{
                this.lbDesconto.setText(String.valueOf(Float.parseFloat(this.campoDesconto.getText())+Float.parseFloat(this.lbDesconto.getText())));
                
            }
            this.lbTotalGeral.setText(String.valueOf(Float.parseFloat(this.lbTotalGeral.getText())-Float.parseFloat(this.lbDesconto.getText())));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Preencha os campos corretamente!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btDescontoActionPerformed

    private void campoRecebidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRecebidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRecebidoActionPerformed

    private void btDeletarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarVendaActionPerformed
        voltarListaEstoque();
        this.reiniciarCampos();
    }//GEN-LAST:event_btDeletarVendaActionPerformed

    private void voltarListaEstoque(){
        String[] produto = new String[this.tbVenda.getRowCount()];
        float[] quantidade = new float[this.tbVenda.getRowCount()];
                
        for(int i=0; i < this.tbVenda.getRowCount(); i++){
            produto[i] = String.valueOf(this.tbVenda.getValueAt(i, 0));
            quantidade[i] = (Integer) this.tbVenda.getValueAt(i, 1);
        }
        this.vendaController.voltarListaEstoque(produto, quantidade);        
    }
    
    private void adicionarProduto(){
        rst=this.vendaController.consultarProduto(this.campoVendaProduto.getText(),Integer.parseInt(this.campoVendaQuantidade.getText()));
        DefaultTableModel model = (DefaultTableModel) this.tbVenda.getModel();
        try{
            if(Integer.parseInt(this.campoVendaQuantidade.getText())<=this.rst.getInt("quantidade")){
                model.addRow(new Object[]{this.rst.getString("nome"), Integer.parseInt(this.campoVendaQuantidade.getText()), this.rst.getFloat("valorUnit"),Integer.parseInt(this.campoVendaQuantidade.getText())*this.rst.getFloat("valorUnit")});
                this.lbTotal.setText(String.valueOf(Float.parseFloat(this.lbTotal.getText())+Float.parseFloat(this.campoVendaQuantidade.getText())*this.rst.getFloat("valorUnit")));
                this.lbTotalGeral.setText(String.valueOf(Float.parseFloat(this.lbTotalGeral.getText())+Float.parseFloat(this.campoVendaQuantidade.getText())*this.rst.getFloat("valorUnit")));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Preencha os campos corretamente!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void btAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddProdutoActionPerformed
        this.adicionarProduto();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        for(int x=0;x<this.tbVenda.getColumnCount();x++){
            this.tbVenda.getColumnModel().getColumn(x).setCellRenderer( centerRenderer );
        }
    }//GEN-LAST:event_btAddProdutoActionPerformed

    private void reiniciarCampos(){
        inicializar = new InicializacaoController(usuario);
        rst=inicializar.inicializacao.getRst();
        try{
            this.nomeCompleto=rst.getString("nomeCompleto");
            this.numVenda=String.valueOf(rst.getInt("idVenda"));
        }
        catch(Exception e){}
        this.lbNumVenda.setText(this.numVenda);
        this.campoVendaProduto.setText("");
        this.campoVendaQuantidade.setText("");
        this.campoCliente.setText("");
        this.campoDesconto.setText("");
        this.campoRecebido.setText("");
        DefaultTableModel dm = (DefaultTableModel) this.tbVenda.getModel();
        int rowCount = dm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
        this.lbDesconto.setText("0");
        this.lbTotal.setText("0");
        this.lbTotalGeral.setText("0");
    }
    
    private void btFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalizarVendaActionPerformed
        try{
            int cont=0;
            for(int i=0; i<this.tbVenda.getRowCount();i++){
                if(tbVenda.getValueAt(i, 0) != null){
                    cont++;
                }
            }
            String pagamento;
            String cliente;
            String produto[]=new String[cont];
            float quantidade[]=new float[cont];
            float precoUnit[]=new float[cont];
            float desconto;
            float precoTotal;
            for(int i=0; i<cont;i++){
                produto[i]=String.valueOf(this.tbVenda.getValueAt(i, 0));
                quantidade[i]=Integer.parseInt(String.valueOf(this.tbVenda.getValueAt(i, 1)));
                precoUnit[i]=Float.parseFloat(String.valueOf(this.tbVenda.getValueAt(i, 2)));

            }
            if(!this.campoDesconto.getText().isEmpty()){
                desconto=Float.parseFloat(this.campoDesconto.getText());
            }
            else{
                desconto=0;
            }
            precoTotal=Float.parseFloat(this.lbTotalGeral.getText());
            pagamento=this.comboPagamento.getSelectedItem().toString();
            if(this.campoCliente.getText().isEmpty()){
               cliente="Não informado";
            }
            else{
                cliente=this.campoCliente.getText();
            }
            this.vendaController.finalizarVenda(produto, quantidade, precoUnit, desconto, precoTotal, pagamento, cliente, this.lbFuncionario.getText());
            JOptionPane.showMessageDialog(null,"TROCO: R$ "+(Float.parseFloat(this.campoRecebido.getText())-Float.parseFloat(this.lbTotalGeral.getText())),"Venda finalizada!",JOptionPane.INFORMATION_MESSAGE);  
            rst=inicializar.inicializacao.getRst();
            try{
                this.nomeCompleto=rst.getString("nomeCompleto");
                this.numVenda=String.valueOf(rst.getInt("count(idVenda)")+1);
            }
            catch(Exception e){}
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Preencha os campos corretamente!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);  
        }
        this.reiniciarCampos();
    }//GEN-LAST:event_btFinalizarVendaActionPerformed

    private void tbVendaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbVendaPropertyChange
        if(this.tbVenda.getSelectedRow()>=0){
            float subtotalAntigo =(Float) this.tbVenda.getValueAt(this.tbVenda.getSelectedRow(), 3);
            this.tbVenda.setValueAt((Integer)this.tbVenda.getValueAt(this.tbVenda.getSelectedRow(), 1)*(Float)(this.tbVenda.getValueAt(this.tbVenda.getSelectedRow(), 2)), this.tbVenda.getSelectedRow(), 3);
            float subtotalNovo = (Float) this.tbVenda.getValueAt(this.tbVenda.getSelectedRow(), 3);
            this.lbTotal.setText(String.valueOf(Float.parseFloat(this.lbTotal.getText())+(subtotalNovo-subtotalAntigo)));
            this.lbTotalGeral.setText(String.valueOf(Float.parseFloat(this.lbTotal.getText())-Float.parseFloat(this.lbDesconto.getText())));
            if((Integer)this.tbVenda.getValueAt(this.tbVenda.getSelectedRow(), 1)>this.quantidadeAntiga){
                this.vendaController.consultarProduto(String.valueOf(this.tbVenda.getValueAt(this.tbVenda.getSelectedRow(), 0)), (Integer)this.tbVenda.getValueAt(this.tbVenda.getSelectedRow(), 1)-this.quantidadeAntiga);
            }
            else{
                this.vendaController.voltarEstoque(String.valueOf(this.tbVenda.getValueAt(this.tbVenda.getSelectedRow(), 0)), (Integer)this.tbVenda.getValueAt(this.tbVenda.getSelectedRow(), 1)-this.quantidadeAntiga);
            }
        }        
    }//GEN-LAST:event_tbVendaPropertyChange

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        try{
            this.lbTotal.setText(String.valueOf(Float.parseFloat(this.lbTotal.getText())-(Float) this.tbVenda.getValueAt(this.tbVenda.getSelectedRow(), 3)));
            if(Float.parseFloat(this.lbTotal.getText())-Float.parseFloat(this.lbDesconto.getText())>=0){
                this.lbTotalGeral.setText(String.valueOf(Float.parseFloat(this.lbTotal.getText())-Float.parseFloat(this.lbDesconto.getText())));
            }
            else{
                this.lbTotalGeral.setText("0");
            }
            
            if(this.lbTotal.getText().equals("0.0")){
                this.lbDesconto.setText("0");
            }
            this.vendaController.voltarEstoque(String.valueOf(this.tbVenda.getValueAt(this.tbVenda.getSelectedRow(), 0)), (Integer)this.tbVenda.getValueAt(this.tbVenda.getSelectedRow(), 1));
            DefaultTableModel model = (DefaultTableModel) this.tbVenda.getModel();
            model.removeRow(this.tbVenda.getSelectedRow());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Selecione algum produto adicionado!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
        }
        

    }//GEN-LAST:event_btRemoverActionPerformed

    private void radioNaoImprimirStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioNaoImprimirStateChanged
        if(this.radioNaoImprimir.isSelected()){
            this.radioImprimir.setSelected(false);
        }
        else{
            this.radioImprimir.setSelected(true);
        }
    }//GEN-LAST:event_radioNaoImprimirStateChanged

    private void radioImprimirStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioImprimirStateChanged
        if(this.radioImprimir.isSelected()){
            this.radioNaoImprimir.setSelected(false);
        }
        else{
            this.radioNaoImprimir.setSelected(true);
        }
    }//GEN-LAST:event_radioImprimirStateChanged

    private void radioNaoImprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioNaoImprimirMouseClicked
        if(this.radioNaoImprimir.isSelected()){
            this.radioNaoImprimir.setSelected(true);
        }
    }//GEN-LAST:event_radioNaoImprimirMouseClicked

    private void radioImprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioImprimirMouseClicked
        if(this.radioImprimir.isSelected()){
            this.radioImprimir.setSelected(true);
        }
    }//GEN-LAST:event_radioImprimirMouseClicked

    private void campoVendaProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoVendaProdutoKeyReleased
        if(this.campoVendaProduto.getText().isEmpty()){
            this.btAddProduto.setEnabled(false);
            this.campoVendaQuantidade.setEnabled(false);
        }
        else{
            this.campoVendaQuantidade.setEnabled(true);
        }
    }//GEN-LAST:event_campoVendaProdutoKeyReleased

    private void campoVendaQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoVendaQuantidadeKeyReleased
        if(this.campoVendaQuantidade.getText().isEmpty()){
            this.btAddProduto.setEnabled(false);
        }
        else{
            this.btAddProduto.setEnabled(true);
        }
    }//GEN-LAST:event_campoVendaQuantidadeKeyReleased
    
    private void tbVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbVendaMouseClicked
        if(this.tbVenda.getSelectedRow()>=0){
            this.btRemover.setEnabled(true);
            this.quantidadeAntiga=(Integer)this.tbVenda.getValueAt(this.tbVenda.getSelectedRow(), 1);
        }
        else{
            this.btRemover.setEnabled(false);
        }
    }//GEN-LAST:event_tbVendaMouseClicked

    private void btRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRemoverMouseClicked
        if(this.tbVenda.getRowCount()>=1){
            this.btRemover.setEnabled(true);
        }
        else{
            this.btRemover.setEnabled(false);
        }
    }//GEN-LAST:event_btRemoverMouseClicked

    private void campoVendaQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoVendaQuantidadeKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            this.adicionarProduto();
        }
    }//GEN-LAST:event_campoVendaQuantidadeKeyPressed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        msgSair.setVisible(true);
    }//GEN-LAST:event_menuSairActionPerformed

    private void btGerClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerClienteActionPerformed
        if(this.permissao){
            InterfaceCliente interfaceCliente = new InterfaceCliente();
            interfaceCliente.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"Você não tem permissão para entrar nessa área!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btGerClienteActionPerformed

    private void campoDescontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDescontoKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') || (c == java.awt.event.KeyEvent.VK_PERIOD)  || (c == java.awt.event.KeyEvent.VK_BACK_SPACE) || (c == java.awt.event.KeyEvent.VK_DELETE)))
            evt.consume();
    }//GEN-LAST:event_campoDescontoKeyTyped

    private void campoRecebidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoRecebidoKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') || (c == java.awt.event.KeyEvent.VK_PERIOD)  || (c == java.awt.event.KeyEvent.VK_BACK_SPACE) || (c == java.awt.event.KeyEvent.VK_DELETE)))
            evt.consume();
    }//GEN-LAST:event_campoRecebidoKeyTyped

    private void campoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoClienteKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c == evt.VK_SPACE ||  c==evt.VK_DELETE ))
            evt.consume();
    }//GEN-LAST:event_campoClienteKeyTyped

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddProduto;
    private javax.swing.JButton btAlternar;
    private javax.swing.JButton btDeletarVenda;
    private javax.swing.JButton btDesconto;
    private javax.swing.JButton btFinalizarVenda;
    private javax.swing.JButton btGerCliente;
    private javax.swing.JButton btGerFornecedor;
    private javax.swing.JButton btGerProduto;
    private javax.swing.JButton btGerRelatorio;
    private javax.swing.JButton btGerUsuario;
    private javax.swing.JButton btNao;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSim;
    private javax.swing.JTextField campoCliente;
    private javax.swing.JTextField campoDesconto;
    private javax.swing.JTextField campoRecebido;
    private javax.swing.JTextField campoVendaProduto;
    private javax.swing.JTextField campoVendaQuantidade;
    private javax.swing.JComboBox<String> comboPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbDesconto;
    private javax.swing.JLabel lbFuncionario;
    private javax.swing.JLabel lbNumVenda;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbTotalGeral;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuSobre;
    private javax.swing.JMenu mnFornecedore;
    private javax.swing.JMenu mnProduto;
    private javax.swing.JMenu mnRelatorio;
    private javax.swing.JMenu mnUsuario;
    private javax.swing.JDialog msgSair;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painelSair;
    private javax.swing.JPanel painelVendas;
    private javax.swing.JRadioButton radioImprimir;
    private javax.swing.JRadioButton radioNaoImprimir;
    private javax.swing.JTable tbVenda;
    // End of variables declaration//GEN-END:variables
}
